### ISSUE TITLE
Grab bag todo list

### ISSUE THREAD

**Issue by katiesaund** [katiesaund/hogwash#2]
- [x] update absolute paths to relative paths
- [x] remove generate dummy data script
- [x] run lintr and covr again
- [x] fully deprecate annotation 
- [x] add an explicit requirement for at least N tips in the tree?

**Comment by katiesaund** [comment]
hogwash() now requires at least 7 tips (7 tips is the number of tips in the example hogwash::tree)
